FROM php:8.4-cli

RUN apt-get update &&  \
    apt upgrade -y && \
    apt-get install -y supervisor tzdata


ENV TZ="Europe/Paris"
RUN echo 'date.timezone = "Europe/Paris"'> /usr/local/etc/php/conf.d/timezone.ini

# extensions php
ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions apcu zip opcache curl sodium intl ldap soap pdo_pgsql pgsql xml oci8

# Nettoyage
RUN rm -rf /var/lib/apt/lists/* && \
    apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Récupération du dossier application
COPY ./ /application
WORKDIR /application/

# composer
ENV COMPOSER_ALLOW_SUPERUSER=1
COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN chmod +x /usr/bin/composer \
    && /usr/bin/composer install --ignore-platform-reqs --optimize-autoloader

# droits du dossier var de symfony
RUN chmod -R a+rw ./var/

# Configuration Supervisor
COPY ./docker/worker/messenger-worker.conf /etc/supervisor/conf.d/


CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/messenger-worker.conf"]