ARG APP_VERSION=latest
#FROM ghcr.io/esupportail/esup-oasis/frontend:${APP_VERSION}
FROM oasis-front-2.2

COPY personnalisation/images/* /app/public/images/
COPY personnalisation/pdf/* /app/public/pdf/