# Build
FROM node:24 AS build

WORKDIR /app

COPY frontend/package.json frontend/yarn.lock ./

## Install dependencies
RUN yarn install --frozen-lockfile

EXPOSE 80
ENV PORT=80

CMD ["yarn", "start", "--port", "80"]
